name: Scheduled Python Task

on:
  workflow_dispatch:   # 手動觸發 (可選)
  schedule:
    - cron: '0 0 * * *'  # UTC+8 上午 8 點整

jobs:
  get-ip:
    runs-on: ubuntu-latest
    outputs:
      runner_ip: ${{ steps.get-ip.outputs.result }} 
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Get runner IP address
        id: get-ip
        run: echo "RUNNER_IP=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

  run_python_task:
    runs-on: ubuntu-latest
    needs: get-ip
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Display runner IP
        run: echo "Runner IP:${{needs.get-ip.outputs.runner_ip}}"
      - name: Run Python script
        run: python autoRank.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
