name: Scheduled Python Task

on:
  workflow_dispatch:   # 手動觸發 (可選)
  schedule:
    - cron: '0 0 * * *'  # UTC+8 上午 8 點整
jobs:
  get-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get runner IP address
        uses: actions/github-script@v6
        with:
          script: |
            const { exec } = require('@actions/exec');
            const ip = await exec('curl', ['https://api.ipify.org']);
            console.log(`Public IP Address: ${ip}`);
  run_python_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Run Python script
        run: python autoRank.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  
