name: Scheduled Python Task

on:
  workflow_dispatch:   # 手動觸發 (可選)
  schedule:
    - cron: '0 0 * * *'  # UTC+8 上午 8 點整

jobs:
  get-ip:
    runs-on: ubuntu-latest
    outputs:
      runner_ip: ${{ steps.get-ip.outputs.RUNNER_IP }}
    steps:
      - name: Get runner IP address
        id: get-ip
        run: |
          echo "RUNNER_IP=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV

  run_python_task:
    runs-on: ubuntu-latest
    needs: get-ip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Run Python script
        run: |
          echo "Runner IP: $RUNNER_IP"
          python autoRank.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
