name: Scheduled Python Task

on:
  workflow_dispatch:   # 手動觸發 (可選)
  schedule:
    - cron: '0 0 * * *'  # UTC+8 上午 8 點整

jobs:
  run_python_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Run Python script
        run: python autoRank.py
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Binance Market Data
          body: Daily binance market data.
          to: jaxman020@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: Daily.txt
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
